"""
Мини-веб-морда для выдачи VLESS-конфига:
  - GET  ${SUB_PATH}/            → HTML-страница с QR + кнопками
  - GET  ${SUB_PATH}/sub         → подписка base64 (v2rayN/v2rayNG/NekoBox)
  - GET  ${SUB_PATH}/clash       → подписка clash.yaml (Hiddify/Mihomo/Stash)
  - GET  ${SUB_PATH}/qr.png      → PNG с QR
  - GET  ${SUB_PATH}/raw         → plain-text vless://...
Дашборд защищён Basic-Auth; sub/clash — только обфускацией пути.
"""
from __future__ import annotations

import base64
import io
import os
import secrets
from functools import wraps
from textwrap import dedent
from urllib.parse import quote, urlencode

import qrcode
from flask import Flask, Response, abort, render_template, request

app = Flask(__name__, template_folder="templates")

# ---------- helpers ----------

def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default)


def _public_host() -> str:
    # Railway → RAILWAY_PUBLIC_DOMAIN. Можно переопределить PUBLIC_HOST.
    return (
        _env("PUBLIC_HOST")
        or _env("RAILWAY_PUBLIC_DOMAIN")
        or request.host.split(":")[0]
    )


def _sub_prefix() -> str:
    return _env("SUB_PATH", "").rstrip("/")


def _vless_link(host: str) -> str:
    uuid = _env("VLESS_UUID")
    ws_path = _env("WS_PATH", "/")
    profile = _env("PROFILE_NAME", "Railway-VPN")

    params = {
        "type": "ws",
        "security": "tls",
        "sni": host,
        "host": host,
        "path": ws_path,
        "encryption": "none",
        "fp": "chrome",
        "alpn": "h2,http/1.1",
    }
    qs = urlencode(params, safe="/:")
    return f"vless://{uuid}@{host}:443?{qs}#{quote(profile)}"


def _clash_yaml(host: str) -> str:
    """
    Конфиг для Mihomo/Clash.Meta/Hiddify со split-routing:
    российские сервисы идут DIRECT, всё остальное — через VPN.
    """
    uuid = _env("VLESS_UUID")
    ws_path = _env("WS_PATH", "/")
    profile = _env("PROFILE_NAME", "Railway-VPN")
    return dedent(f"""\
        # Mihomo / Clash.Meta / Hiddify config with RU split-routing
        # Generated by Railway-VPN-Deploy
        mixed-port: 7890
        allow-lan: false
        mode: rule
        log-level: warning
        ipv6: false

        dns:
          enable: true
          ipv6: false
          enhanced-mode: fake-ip
          fake-ip-range: 198.18.0.1/16
          fake-ip-filter:
            - '*.lan'
            - '*.local'
            - localhost.*
            - '+.ru'
            - '+.su'
            - '+.рф'
          default-nameserver:
            - 1.1.1.1
            - 8.8.8.8
          nameserver:
            - https://cloudflare-dns.com/dns-query
            - https://dns.google/dns-query
          fallback:
            - tls://1.1.1.1:853
            - tls://8.8.8.8:853
          fallback-filter:
            geoip: true
            geoip-code: RU
            ipcidr:
              - 240.0.0.0/4

        proxies:
          - name: {profile!r}
            type: vless
            server: {host}
            port: 443
            uuid: {uuid}
            udp: false
            tls: true
            network: ws
            servername: {host}
            client-fingerprint: chrome
            ws-opts:
              path: {ws_path!r}
              headers:
                Host: {host}

        proxy-groups:
          - name: PROXY
            type: select
            proxies:
              - {profile!r}
              - DIRECT

        rules:
          # --- DIRECT: локальные/частные сети ---
          - GEOIP,LAN,DIRECT,no-resolve
          - GEOIP,PRIVATE,DIRECT,no-resolve
          - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
          - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
          - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
          - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve

          # --- DIRECT: РФ-зоны и национальные суффиксы ---
          - DOMAIN-SUFFIX,ru,DIRECT
          - DOMAIN-SUFFIX,su,DIRECT
          - DOMAIN-SUFFIX,xn--p1ai,DIRECT
          - DOMAIN-SUFFIX,xn--80aswg,DIRECT
          - DOMAIN-SUFFIX,xn--80adxhks,DIRECT
          - DOMAIN-SUFFIX,xn--90ais,DIRECT
          - DOMAIN-SUFFIX,by,DIRECT

          # --- DIRECT: главные сервисы РФ ---
          - DOMAIN-KEYWORD,sber,DIRECT
          - DOMAIN-KEYWORD,yandex,DIRECT
          - DOMAIN-KEYWORD,ozon,DIRECT
          - DOMAIN-KEYWORD,wildberries,DIRECT
          - DOMAIN-KEYWORD,wbbasket,DIRECT
          - DOMAIN-KEYWORD,avito,DIRECT
          - DOMAIN-KEYWORD,mail-ru,DIRECT
          - DOMAIN-SUFFIX,mail.ru,DIRECT
          - DOMAIN-SUFFIX,vk.com,DIRECT
          - DOMAIN-SUFFIX,vk.ru,DIRECT
          - DOMAIN-SUFFIX,vkuseraudio.net,DIRECT
          - DOMAIN-SUFFIX,vkuservideo.net,DIRECT
          - DOMAIN-SUFFIX,ok.ru,DIRECT
          - DOMAIN-SUFFIX,kinopoisk.ru,DIRECT
          - DOMAIN-SUFFIX,rutube.ru,DIRECT
          - DOMAIN-SUFFIX,gosuslugi.ru,DIRECT
          - DOMAIN-SUFFIX,nalog.ru,DIRECT
          - DOMAIN-SUFFIX,tinkoff.ru,DIRECT
          - DOMAIN-SUFFIX,t-bank.ru,DIRECT
          - DOMAIN-SUFFIX,vtb.ru,DIRECT
          - DOMAIN-SUFFIX,alfabank.ru,DIRECT
          - DOMAIN-SUFFIX,raiffeisen.ru,DIRECT
          - DOMAIN-SUFFIX,gazprombank.ru,DIRECT
          - DOMAIN-SUFFIX,rbc.ru,DIRECT
          - DOMAIN-SUFFIX,2gis.ru,DIRECT
          - DOMAIN-SUFFIX,2gis.com,DIRECT
          - DOMAIN-SUFFIX,hh.ru,DIRECT
          - DOMAIN-SUFFIX,cian.ru,DIRECT
          - DOMAIN-SUFFIX,drom.ru,DIRECT

          # --- DIRECT: всё остальное русское по GeoIP ---
          - GEOIP,RU,DIRECT

          # --- PROXY: всё остальное через VPN ---
          - MATCH,PROXY
        """)


def _check_auth(username: str, password: str) -> bool:
    expected_user = _env("BASIC_AUTH_USER", "admin")
    expected_pass = _env("BASIC_AUTH_PASS", "")
    if not expected_pass:
        return False
    return secrets.compare_digest(username, expected_user) and secrets.compare_digest(
        password, expected_pass
    )


def _auth_required():
    return Response(
        "Authentication required",
        401,
        {"WWW-Authenticate": 'Basic realm="VPN config"'},
    )


def basic_auth(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        auth = request.authorization
        if not auth or not _check_auth(auth.username or "", auth.password or ""):
            return _auth_required()
        return fn(*args, **kwargs)

    return wrapper


# ---------- routes ----------

@app.get("/healthz")
def healthz():  # вызывается Caddy / Railway healthcheck
    return "ok", 200


@app.get(f"{_sub_prefix() or ''}/")
@basic_auth
def dashboard():
    host = _public_host()
    link = _vless_link(host)
    pref = _sub_prefix()
    return render_template(
        "config.html",
        link=link,
        sub_url=f"https://{host}{pref}/sub",
        clash_url=f"https://{host}{pref}/clash",
        host=host,
        qr_url=f"{pref}/qr.png",
        raw_url=f"{pref}/raw",
        profile=_env("PROFILE_NAME", "Railway-VPN"),
    )


@app.get(f"{_sub_prefix() or ''}/raw")
@basic_auth
def raw():
    return Response(_vless_link(_public_host()) + "\n", mimetype="text/plain")


@app.get(f"{_sub_prefix() or ''}/qr.png")
@basic_auth
def qr_png():
    link = _vless_link(_public_host())
    img = qrcode.make(link, box_size=8, border=2)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return Response(buf.read(), mimetype="image/png")


@app.get(f"{_sub_prefix() or ''}/sub")
def subscription():
    """
    Эндпоинт подписки v2ray-формата (base64 со списком vless://).
    Понимают v2rayN, v2rayNG, NekoBox, Streisand.
    Basic-Auth НЕ ставим (мобильные клиенты не умеют его в подписке),
    безопасность держится на длинном случайном ${SUB_PATH}.
    """
    payload = _vless_link(_public_host()) + "\n"
    encoded = base64.b64encode(payload.encode()).decode()
    resp = Response(encoded, mimetype="text/plain; charset=utf-8")
    resp.headers["Profile-Update-Interval"] = "24"
    resp.headers["Subscription-Userinfo"] = "upload=0; download=0; total=0; expire=0"
    return resp


@app.get(f"{_sub_prefix() or ''}/clash")
def clash_subscription():
    """
    Подписка в формате Mihomo/Clash.Meta с готовыми правилами split-routing:
    российские сервисы идут DIRECT, всё остальное — через VPN.
    Понимают Hiddify, Mihomo Party, Stash, ClashX Meta, v2rayN (Pro).
    """
    body = _clash_yaml(_public_host())
    resp = Response(body, mimetype="text/yaml; charset=utf-8")
    resp.headers["Content-Disposition"] = (
        f'inline; filename="{_env("PROFILE_NAME", "Railway-VPN")}.yaml"'
    )
    resp.headers["Profile-Update-Interval"] = "24"
    resp.headers["Subscription-Userinfo"] = "upload=0; download=0; total=0; expire=0"
    return resp


# Fallback на корень — чтобы не было 404 при пустом ${SUB_PATH}.
if _sub_prefix():
    @app.get("/")
    def _root_redirect():
        # На корне Flask отвечать не должен — Caddy его не маршрутизирует сюда,
        # но если кто-то залез — притворимся 404.
        abort(404)


if __name__ == "__main__":
    # bind только на loopback — наружу торчит только Caddy.
    # Порт берём из FLASK_PORT, чтобы не конфликтовать с Railway $PORT,
    # на котором висит Caddy.
    port = int(os.environ.get("FLASK_PORT", "10001"))
    app.run(host="127.0.0.1", port=port, threaded=True)
